---
- name: Upgrade all packages from OS
  apt:
    name: '*'
    state: latest
- name: Git installation
  apt:
    name: git
    state: latest
- name: Setup Ansible hosts 
  lineinfile: 
    dest: /etc/hosts
    state: present
    line: "{{item}}"
  with_items:
    - 192.168.56.2 control-node
    - 192.168.56.3 app
    - 192.168.56.4 db