---
- name: Setup all database servers
  hosts: db
  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    dbname: "db"
    dbusername: "root"
    dbpassword: "root"
  roles:
    - default-os-setup
    - role: geerlingguy.mysql