---
- name: Setup all database servers
  hosts: db
  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    dbname: "db"
    dbusername: "root"
    dbpassword: "root"
  tasks:
    - name: Setup Ansible hosts
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.56.2 control-node
        - 192.168.56.3 app
        - 192.168.56.4 db
  roles:
    - default-os-setup
    - role: geerlingguy.mysql