Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "db"
  config.vm.network "private_network", ip: "192.168.56.4"
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.provision "shell", path: "provision.sh"
end
